# **LAB SHEET 5**
### **ADITYA PAL  CU24250198**
##### **BTECH CSE 6-03-2025**

##Numpy Basics


##Task 1->Import the NumPy library and print its version

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


##Task 2->Create a NumPy array from a list and display its properties.

In [ ]:
ar=np.array([1,2,3,4,5])
print("Numpu array:",ar)
print("Shape:",ar.shape)
print("Size:",ar.size)
print("Data Type:",ar.dtype)
print("Dimensions:",ar.ndim)
print("Item Size(Bytes):",ar.itemsize)

Numpu array: [1 2 3 4 5]
Shape: (5,)
Size: 5
Data Type: int64
Dimensions: 1
Item Size(Bytes): 8


##Task 3->Generate an array of zeros, ones, and random values.

In [ ]:
arr=np.zeros((2,2))  #contain 0 only
print(" Zeros array:\n",arr)

arr=np.ones((2,2))#contain 1 only
print("Ones array:\n",arr)

arr=np.random.rand(3,3) #contain value between 0&1
print("1 Random value:\n",arr)

arr=np.random.randn(3,3) #contain value from normal distribution
print("2 Random value:\n",arr)

arr=np.random.randint(1,100,(3,3))  #contain value Between given range
print("3 Random value\n",arr)

 Zeros array:
 [[0. 0.]
 [0. 0.]]
Ones array:
 [[1. 1.]
 [1. 1.]]
1 Random value:
 [[0.63515781 0.93548505 0.69261564]
 [0.77702163 0.27433454 0.60973043]
 [0.57986664 0.48356962 0.83998921]]
2 Random value:
 [[-0.54301433  0.83520473 -0.18434037]
 [-0.87819586  0.82745262  1.78935525]
 [-1.71999208 -2.17270061 -0.00455051]]
3 Random value
 [[28 70 66]
 [58 77 76]
 [62 83  4]]


##Task 4->Reshape an array into a 4x5 matrix

In [ ]:
arrr=np.arange(20)
print("Array:\n",arrr)
arrr=arrr.reshape(4,5)
print("New Array:\n",arrr)

Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
New Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


##Task 5->Slice the matrix to extract specific rows and columns.

In [ ]:
print("1D ARRAY\n")
arr=np.array([10,20,30,40,50])
print(arr[1:4])
print(arr[-4:-1])
print(arr[1:])
print(arr[:3])
print(arr[::-1])  #reverse
print(arr[::2])   #every second element
#[start,end,step]
#[by deafault 0 ,default end is last,default step is 1]

1D ARRAY

[20 30 40]
[20 30 40]
[20 30 40 50]
[10 20 30]
[50 40 30 20 10]
[10 30 50]


In [ ]:
print("2D ARRAY\n")
arr2d=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr2d[0:2,1:3])  #[row_start:row_end,col_start:col_end]
print(arr2d[1:3,1:3])
print(arr2d[0:2,0:2])

2D ARRAY

[[2 3]
 [5 6]]
[[5 6]
 [8 9]]
[[1 2]
 [4 5]]


##Task 6->Stack two arrays vertically and horizontally

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print("Result Vertically:\n",result)

Result:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
result=np.hstack((arr1,arr2))
print("Result Horizontally:\n",result)


Result Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


##Task 7->Perform element-wise arithmetic operations.

In [ ]:
ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
print("+ operator\n",ar1+ar2)
print("- operator\n",ar2-ar1)
print("* operator\n",ar1*ar2)
print("/ operator\n",ar1/ar2)
print("** operator\n",ar1**ar2)  #exponantial operator

+ operator
 [5 7 9]
- operator
 [3 3 3]
* operator
 [ 4 10 18]
/ operator
 [0.25 0.4  0.5 ]


##Task 8->Demonstrate broadcasting.


####->BROADCASTING = IT ALLOW NUMPY TO PERFOMN OPERATION BETWEEN ARRAY OF DIFFERENT DIMENSIONS

####->Smaller ar2 is broadcasted to larger ar1

In [ ]:
ar1=np.array([[1,2,3],[1,1,1]])
ar2=np.array([4,5,6])
print("+ operator\n",ar1+ar2)
print("- operator\n",ar2-ar1)
print("* operator\n",ar1*ar2)
print("/ operator\n",ar1/ar2)

+ operator
 [[5 7 9]
 [5 6 7]]
- operator
 [[3 3 3]
 [3 4 5]]
* operator
 [[ 4 10 18]
 [ 4  5  6]]
/ operator
 [[0.25       0.4        0.5       ]
 [0.25       0.2        0.16666667]]


###->Broadcasting scalar with array

In [ ]:
arr=np.array([1,2,3])
print(arr+10)

[11 12 13]


##Task 9->Compute sum, mean, and standard deviation.

In [ ]:
arr=np.array([1,2,3,4,5])
print("Sum of elements:",arr.sum())
print("mean of elements:",arr.mean())
print("standard deviation of elements:",arr.std())


Sum of elements: 15
mean of elements: 3.0
standard deviation of elements: 1.4142135623730951


##Task 10->Generate and plot a histogram.


In [ ]:
data=np.array([45,47,50,55,60,62,65,68,70,75,78,80,82,85,90])
hist,bin = np.histogram(data,bins=5) #devide data into five equal interval
print("Histogram:",hist)  #hist give the count of value in each bin
print("Bins:",bin)  #show range of each bin