# **LAB SHEET 6**
### **ADITYA PAL  CU24250198**
##### **BTECH CSE 6-03-2025**

##Advance Numpy Operationa

##Task 1->Generate a 5x5 matrix of random integers.

In [ ]:
import numpy as np
print("TYPE 1\n")
ar1=np.random.rand(5,5)
print(ar1)
print("TYPE 2\n")
ar2=np.random.randn(5,5)
print(ar2)
print("TYPE 3\n")
ar3=np.random.randint(1,100,(5,5))
print(ar3)

TYPE 1

[[0.632121   0.64328605 0.56233211 0.40788476 0.6441552 ]
 [0.05147809 0.4714485  0.33454339 0.32827163 0.89186244]
 [0.92399469 0.64733102 0.96696844 0.31812815 0.70137776]
 [0.71801023 0.0640572  0.00453314 0.8936476  0.49721331]
 [0.68681435 0.93145872 0.74930727 0.35842264 0.6318022 ]]
TYPE 2

[[-0.71394637 -1.70318675 -0.07951264 -0.38524749 -0.76578601]
 [-1.00686556  0.40987661  0.05407613  0.12821842 -1.42454905]
 [-1.80433061 -0.57125655 -1.14479838  0.91539842  1.58255987]
 [-1.30605263  0.4023912  -1.64652849 -0.49407888  0.47811827]
 [ 1.62529649 -0.74687985 -0.24135844 -1.97668599  1.00161993]]
TYPE 3

[[ 1 37 56 77 24]
 [88 92 56 53 61]
 [16 44 60 75 34]
 [85 21 23 76 28]
 [26 17 43 50 57]]


##Task 2->Compute statistical measures.


In [ ]:
import numpy as np
ar=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.mean(ar))
print(np.median(ar))
print(np.std(ar))
print(np.var(ar))
print(np.min(ar))
print(np.max(ar))
print(np.percentile(ar,25))


55.0
55.0
28.722813232690143
825.0
10
100
32.5


##Task 3->Find max/min values along rows and columns.

In [2]:
arr = np.array([[3, 7, 1],
                [10, 5, 8],
                [6, 2, 9]])

max_col = np.max(arr, axis=0)  # Finding max values along column
max_row = np.max(arr, axis=1)  # Finding max values along rows
min_col = np.min(arr, axis=0)  # Finding min values along columns
min_row = np.min(arr, axis=1) # Finding min values along rows

print("Max along columns:", max_col)
print("Max along rows:", max_row)
print("Min along columns:", min_col)
print("Min along rows:", min_row)

Max along columns: [10  7  9]
Max along rows: [ 7 10  9]
Min along columns: [3 2 1]
Min along rows: [1 5 2]


##task 4->Perform matrix multiplication.

In [ ]:
ar1=np.array([[1,2],[2,3]])
ar2=np.array([[5,6],[7,8]])
print(ar1@ar2)
print(np.matmul(ar1,ar2))
print(np.dot(ar1,ar2))

[[19 22]
 [31 36]]
[[19 22]
 [31 36]]
[[19 22]
 [31 36]]


##Task 5->Compute determinant and inverse.

In [3]:
import numpy as np
A = np.array([[4, 7],
              [2, 6]])

# Compute determinant
det= np.linalg.det(A)

# Compute inverse
inv= np.linalg.inv(A)

print("Determinant of A:", det)
print("Inverse of A:\n", inv)


Determinant of A: 10.000000000000002
Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


##Task 6->Calculate eigenvalues and eigenvectors.

In [4]:
import numpy as np
A = np.array([[4, -2],
              [1,  1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix A:
 [[ 4 -2]
 [ 1  1]]
Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


##Task 7->Demonstrate np.corrcoef().

In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([2,4,6,8,10])
correlation=np.corrcoef(x,y)  # Show relation btw two dataset
print(correlation)
#A Coffecient close to 1 indicate a strong positive correlation
#(0 to 1)so positive corelated
#(-1 to 0) negatice related

##Task 8->Normalize a NumPy array.

In [5]:
import numpy as np

arr = np.array([3, 7, 1, 10, 5])


arr_norm = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

print("Original array:", arr)
print("normalized array:", arr_norm)


Original array: [ 3  7  1 10  5]
normalized array: [0.22222222 0.66666667 0.         1.         0.44444444]


##Task 9->Apply boolean indexing.

In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[arr>25])

[30 40 50]


##Task 10->Solve a system of linear equations.


In [7]:
import numpy as np

A = np.array([[2, 3],  # Coefficient matrix (A)
              [5, 7]])


B = np.array([8, 19])  # Constant matrix (B)

X = np.linalg.solve(A, B)   # Solve for x (unknown variables)

print("Solution for x and y:", X)


Solution for x and y: [1. 2.]
